### ISSUE TITLE
não encontrei o arquivo .sql

### ISSUE THREAD

**Issue by evertonterra** [rmsaitam/agenda-compromissos#1]
não encontrei o arquivo para importar para o banco de dados
seria possivel colocar ele dentro dos arquivos disponiveis?

**Comment by rmsaitam** [comment]
Esse projeto eu utilizei migrations com a biblioteca Phinx do PHP, nisso facilita, basta criar o  banco de dados, executar o composer install, criar o arquivo de configuração phinx.yaml  com o comando vendor/bin/phinx init

phinx.yaml
```
development:
        adapter: mysql
        host: localhost
        name: agendacompromissos
        user: usuario
        pass: 'senha'
        port: 3306
        charset: utf8
```

PS: em user e pass coloque a credencial do usuário MySQL que instalou em seu ambiente

Renomear o arquivo config/config-exemplo.php para config/config.php e coloque o usuário/senha do banco de dados mv config/config-exemplo.php config/config.php
Em DB_USER e DB_PASS deve ser colocado o usuário e senha do banco de dados

Estando com o banco de dados criado com nome agendacompromissos, o usuário com os privilégios  e adicionado as credencias do usuário/senha do banco de dados no arquivo phinx.yml, pode executar o migrations para criar as tabelas. vendor/bin/phinx migrate

Se quiser configurar o projeto no Vhost, os procedimentos está no README.md ou pode executar o webserver interno do PHP

`php -S 127.0.0.1:8000` 

No browser http://127.0.0.1:8000
Feito!
